# Site
repository: https://github.com/alexandra-nazerai
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alexandra Nazerai
title: Researcher
email: nazerai.alexandra@gmail.com
website: https://github.com/alexandra-nazerai

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  alexandra-nazerai
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  (Under construction ..)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: (under construction ...)
        link: ...
        # link_text: Project Website
        additional_links:
          - title:  ....
            icon: fab fa-github
            url: ...
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          ...

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (under construction ...)
        link: ...
        # link_text: boringcompany.com
        sub_title: ...
        caption: ...
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
            ...

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Southampton (UK)
        caption: PhD
        sub_title: ...
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          ...

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      (under construction ...)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
